In [40]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y

In [41]:
# Set notebook display
%matplotlib inline
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('retina')

# import data analysis libraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [42]:
# read normalized data for SAW and WP method
normalized_data_path = os.path.join(os.path.abspath('..'), 'data', 'normalized_data.csv')

if os.path.exists(normalized_data_path):
    print('File paht:', normalized_data_path)
else:
    print('Check the data path!')

normalized_data = pd.read_csv(normalized_data_path, index_col = 0)
normalized_data.head()

File paht: /Users/rolf/Downloads/noncomp/rank/data/normalized_data.csv

,EnerCon,RD,Loan,TerInd,PubSpa,WatCon,Engle,Unemp,PopDen,GradeII,SolWas,WasWater,ConWas,PubBus,PasInt
City,,,,,,,,,,,,,,,
Beijing,0.893634,1.000000,0.554920,1.000000,0.466294,0.849516,0.517706,1.000000,0.847562,0.328413,0.804689,0.598266,0.579581,0.159141,0.106449
Tianjin,0.817083,0.498335,0.392968,0.300174,0.160638,0.897654,0.417939,0.214286,0.829570,0.354244,0.982734,1.000000,0.555371,0.099644,0.041950
Shijiazhuang,0.599517,0.561820,0.356321,0.448893,0.278362,0.963315,0.781277,0.175000,0.691098,0.066421,0.922382,0.880058,0.380647,0.080405,0.049464
Qinhuangdao,0.659952,0.558269,0.458958,0.672470,1.000000,0.811938,0.879188,0.260714,0.705688,0.590406,0.445588,0.953179,1.000000,0.051713,0.026325
Baoding,0.651894,0.567148,0.413456,0.000000,0.138770,0.950802,1.000000,0.028571,0.379772,0.000000,0.781403,0.751156,0.455508,0.186165,0.035300

In [43]:
# read nest weights for SAW and WP method
nest_weight_path = os.path.join(os.path.abspath('..'), 'data', 'nest_weight.csv')

if os.path.exists(nest_weight_path):
    print('File paht:', nest_weight_path)
else:
    print('Check the data path!')

nest_weight = pd.read_csv(nest_weight_path, index_col = 0)
nest_weight

File paht: /Users/rolf/Downloads/noncomp/rank/data/nest_weight.csv

,EnerCon,RD,Loan,TerInd,PubSpa,WatCon,Engle,Unemp,PopDen,GradeII,SolWas,WasWater,ConWas,PubBus,PasInt
Weight,0.0625,0.0625,0.0625,0.0625,0.05,0.05,0.05,0.05,0.05,0.0625,0.0625,0.0625,0.0625,0.125,0.125

# SAW

In [44]:
saw_matrix = normalized_data.copy()
saw_matrix['SAW'] = saw_matrix.dot(nest_weight.T)

saw_matrix['Rank'] = saw_matrix['SAW'].rank(ascending = False)

saw_matrix.head()

,EnerCon,RD,Loan,TerInd,PubSpa,WatCon,Engle,Unemp,PopDen,GradeII,SolWas,WasWater,ConWas,PubBus,PasInt,SAW,Rank
City,,,,,,,,,,,,,,,,,
Beijing,0.893634,1.000000,0.554920,1.000000,0.466294,0.849516,0.517706,1.000000,0.847562,0.328413,0.804689,0.598266,0.579581,0.159141,0.106449,0.577222,4.0
Tianjin,0.817083,0.498335,0.392968,0.300174,0.160638,0.897654,0.417939,0.214286,0.829570,0.354244,0.982734,1.000000,0.555371,0.099644,0.041950,0.450010,26.0
Shijiazhuang,0.599517,0.561820,0.356321,0.448893,0.278362,0.963315,0.781277,0.175000,0.691098,0.066421,0.922382,0.880058,0.380647,0.080405,0.049464,0.424190,37.0
Qinhuangdao,0.659952,0.558269,0.458958,0.672470,1.000000,0.811938,0.879188,0.260714,0.705688,0.590406,0.445588,0.953179,1.000000,0.051713,0.026325,0.526307,6.0
Baoding,0.651894,0.567148,0.413456,0.000000,0.138770,0.950802,1.000000,0.028571,0.379772,0.000000,0.781403,0.751156,0.455508,0.186165,0.035300,0.378864,39.0

In [39]:
saw_matrix.to_csv('../results/saw_wp/saw.csv')

# WP

In [51]:
wp_matrix = normalized_data.copy()

In [53]:
m, n = wp_matrix.shape

for row in range(m):
    for column in range(n):
        wp_matrix.iloc[row, column] = wp_matrix.iloc[row, column]** nest_weight.iloc[0, column]
        
wp_matrix.head()

,EnerCon,RD,Loan,TerInd,PubSpa,WatCon,Engle,Unemp,PopDen,GradeII,SolWas,WasWater,ConWas,PubBus,PasInt
City,,,,,,,,,,,,,,,
Beijing,0.992996,1.000000,0.963861,1.000000,0.962571,0.991879,0.967618,1.000000,0.991765,0.932774,0.986511,0.968402,0.966484,0.794736,0.755775
Tianjin,0.987453,0.957404,0.943295,0.927547,0.912625,0.994616,0.957317,0.925869,0.990701,0.937198,0.998912,1.000000,0.963910,0.749560,0.672731
Shijiazhuang,0.968529,0.964606,0.937541,0.951172,0.938060,0.998133,0.987735,0.916541,0.981696,0.844100,0.994963,0.992046,0.941418,0.729727,0.686729
Qinhuangdao,0.974360,0.964223,0.952491,0.975505,1.000000,0.989638,0.993583,0.934993,0.982722,0.967602,0.950733,0.997007,1.000000,0.690557,0.634666
Baoding,0.973612,0.965175,0.946296,0.000000,0.905972,0.997481,1.000000,0.837137,0.952744,0.000000,0.984702,0.982275,0.952042,0.810471,0.658372

In [59]:
wp_matrix['WP'] = wp_matrix.sum(axis = 1)
wp_matrix['Rank'] = wp_matrix['WP'].rank(ascending = False)
wp_matrix.head()

,EnerCon,RD,Loan,TerInd,PubSpa,WatCon,Engle,Unemp,PopDen,GradeII,SolWas,WasWater,ConWas,PubBus,PasInt,WP,Rank
City,,,,,,,,,,,,,,,,,
Beijing,0.992996,1.000000,0.963861,1.000000,0.962571,0.991879,0.967618,1.000000,0.991765,0.932774,0.986511,0.968402,0.966484,0.794736,0.755775,28.550744,1.0
Tianjin,0.987453,0.957404,0.943295,0.927547,0.912625,0.994616,0.957317,0.925869,0.990701,0.937198,0.998912,1.000000,0.963910,0.749560,0.672731,27.838276,23.0
Shijiazhuang,0.968529,0.964606,0.937541,0.951172,0.938060,0.998133,0.987735,0.916541,0.981696,0.844100,0.994963,0.992046,0.941418,0.729727,0.686729,27.665991,28.0
Qinhuangdao,0.974360,0.964223,0.952491,0.975505,1.000000,0.989638,0.993583,0.934993,0.982722,0.967602,0.950733,0.997007,1.000000,0.690557,0.634666,28.016160,14.0
Baoding,0.973612,0.965175,0.946296,0.000000,0.905972,0.997481,1.000000,0.837137,0.952744,0.000000,0.984702,0.982275,0.952042,0.810471,0.658372,23.932556,39.0

In [60]:
wp_matrix.to_csv('../results/saw_wp/wp.csv')

# correlation analysis:
data:
saw_rank, wp_rank, average outranking rank(equal threshod, indifference_threhold_00_10_phi0.3, indifference_threhold_00_10_phi0.6, preference_threshod_00_10_phi0.3, preference_threshod_00_10_phi0.6)

In [62]:
# read nest weights for SAW and WP method
corr_matrix_path = os.path.join(os.path.abspath('..'), 'results','correlation_analysis',
                                'correlation_analysis.csv')

if os.path.exists(corr_matrix_path):
    print('File paht:', corr_matrix_path)
else:
    print('Check the data path!')

corr_matrix = pd.read_csv(corr_matrix_path, index_col = 0)
corr_matrix.head()

File paht: /Users/rolf/Downloads/noncomp/rank/results/correlation_analysis/correlation_analysis.csv

,SAW,WP,equal_threshold_aver,indiff_threshold03_aver1,indiff_threshold06_aver1,pref_threshold03_aver,pref_threshold06_aver
Beijing,4,1,1.181818,1.583333,1.000000,1.818182,1.000000
Tianjin,26,23,32.727273,22.776515,15.295455,37.818182,25.818182
Shijiazhuang,37,28,30.272727,22.428030,16.863636,34.090909,21.545455
Qinhuangdao,6,14,21.454545,16.943182,10.363636,27.818182,16.363636
Baoding,39,39,32.636364,24.846591,22.068182,31.454545,27.090909

In [ ]:
columns_name = [r'$SAW$', r'$WP$', r'$EqTh-Average$', r'$IndiffTh-\phi_\frac{1}{3}-Average$',
               r'$IndiffTh-\phi_\frac{1}{6}-Average$', r'$PreTh-\phi_\frac{1}{3}-Average$',
               r'$PreTh-\phi_\frac{1}{6}-Average$]